#%RAML 1.0 Library

uses:
  extension: extension.raml

types:
  giskeKeyHeader:
    displayName: GISKE Key Header
    type: extension.extensible
    description: Global Interoperable Secure Key Exchange Key Block
      Specification V2.3a Key Header. Before a key in the Key Block format is
      used in a Tamper Resistant Security Module (TRSM), the content of the
      header block must be validated to ensure the correct usage is enforced.
      The “Key Usage” byte is typically checked first followed by the “Algorithm”
      byte. The other header bytes may or may not be checked depending on the
      key usage and the algorithm used.
    properties:
      keyUsage: giskeKeyUsageEnum | string
      algorithm: giskeAlgorithmEnum | string
      modeOfUse: giskeModeOfUseEnum | string
      exportability: giskeExportabilityEnum | string

  giskeKeyUsageEnum:
    displayName: GISKE key usage
    description: >
      GISKE Specification 2.3a - Key Block header bytes 5 and 6.
      Note that these usages may work for both symmetric and asymmetric keys.
      This list of usages is not intended to be exhaustive. Future versions may
      include other key usages types.
    enum: [
      dataEncryption, controlVector, keyEncryptionOrWrapping,
      macGeneration, macVerification, pinEncryption,
      pinVerification, cardVerificationKey, keyComponent,
      baseDerivationKey, iso-9791-1-mac1-56, iso-9791-1-mac1-112,
      iso-9791-1-mac2-112, iso-9791-1-mac3-112, iso-9791-1-mac4-112,
      iso-9791-1-mac5-56, iso-9791-1-mac5-112
    ]

  giskeAlgorithmEnum:
    displayName: GISKE algorithms
    description: GISKE Specification 2.3a - Key Block header byte 7
    enum: [ 3des, aes, des, dsa, ellipticCurve, rsa, unknownOrUnspecified ]

  giskeModeOfUseEnum:
    displayName: GISKE mode of use
    description: GISKE Specification 2.3a - Key Block header byte 8
    enum: [ noSpecialRestrictions, encryptOnly, decryptOnly,
      signatureOnly, macGenerate, macVerify, macCalculate, iv ]

  giskeExportabilityEnum:
    displayName: GISKE Exportability
    description:  >
      GISKE Specification 2.3a - Key Block header byte 27.
      “Exportability” refers to transfer outside the system in which the key is
      found. Secure backup of a key may be allowed, depending on local rules.
      Flags in this field indicate special types of keys that require unusual
      handling. Any key that does not follow normal security assumptions should
      have a notation in this field. This may mean that the key should be less
      trusted, like a CAPI key, or that the key assumes a high degree of trust,
      such as a CA key. In general, a letter in this column means that future
      developers should check the definition of this type of key carefully.
    enum: [ sensitive, exportable, nonExportable ]

  algorithmSoftEnum:
    type: algorithmEnum | string

  algorithmEnum:
    enum: [ 3des, aes, des, dsa, ellipticCurve, rsa, unknownOrUnspecified ]
