#%RAML 1.0 Library
usage: additional base types

types:

  decimal:
    description: XML "xsd-decimal" rules apply. YAML does not support decimal type natively, so we use a string.
    type: string

  monetaryAmount:
    description: Common definition of monetary amount data type.
    type: decimal
