#%RAML 1.0 Library

types:
  severityEnum:
    displayName: syslogd severity levels
    description: extracted verbatim from syslogd manual
    enum:
      ["emerg","alert","err","warning","notice","info","debug"]
