#%RAML 1.0 Trait

queryParameters:
  includeDisabled:
    displayName: Include disabled items in the response
    type: boolean
    description: select true to include disabled items in the response records.
    example: true
    required: false
