#%RAML 1.0 Trait

queryParameters:
  view:
    displayName: Set of fields to display if verbose is requested, current stored configuration will be returned.
    type: string
    enum: ["verbose", "basic"]
    required: false
